# Generated by Django 2.2.13 on 2022-01-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
