# Generated by Django 2.2.13 on 2022-01-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_shopproduct_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='file',
        ),
        migrations.AddField(
            model_name='shop',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
