# Generated by Django 2.2.13 on 2022-01-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220130_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='file',
            field=models.FileField(null=True, upload_to='uploaded_data'),
        ),
    ]
